### ISSUE TITLE
Office Addin SSO Node JS - 404 on latest version

### ISSUE THREAD

**Issue by davidk43** [OfficeDev/Office-Add-in-samples#402]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

Hi I've been trying to update this tutorial since the recent token revisions and I can't get it to sideload at all. Suspect I'm being dumb but not finding any help out there. I've retraced my steps several times with a fresh pull and keep hitting the same load issue. I have other samples sideloading fine, any pointers please?:

NotFoundError: Not Found
    at C:\Office Addins\SSO\app.js:62:8
    at Layer.handle [as handle_request] (C:\Office Addins\SSO\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Office Addins\SSO\node_modules\express\lib\router\index.js:317:13)
    at C:\Office Addins\SSO\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Office Addins\SSO\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Office Addins\SSO\node_modules\express\lib\router\index.js:275:10)
    at C:\Office Addins\SSO\app.js:41:5
    at Layer.handle [as handle_request] (C:\Office Addins\SSO\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Office Addins\SSO\node_modules\express\lib\router\index.js:317:13)
    at C:\Office Addins\SSO\node_modules\express\lib\router\index.js:284:7

**Comment by davidk43** [comment]
Closing this, issue has gone (still no idea tho!) - apologies.

**Comment by michelleranmsft** [comment]
Good to hear the issue was resolved! If you run into this problem again and feel this issue needs to be re-opened, please let us know.
